# Generated by Django 4.2.7 on 2024-03-27 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Design', 'Design'), ('Customer Service', 'Customer Service'), ('Backoffice', 'Backoffice'), ('Meida', 'Media'), ('Marketing', 'Marketing'), ('Sales', 'Sales')], default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
