# Generated by Django 4.2.7 on 2024-03-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0002_task_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Backoffice', 'Backoffice'), ('Customer Service', 'Customer Service'), ('Sales', 'Sales'), ('Design', 'Design'), ('Marketing', 'Marketing'), ('Media', 'Media')], max_length=25),
        ),
    ]
