# Generated by Django 4.2.7 on 2024-03-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0005_alter_task_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subtask',
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Media', 'Media'), ('Sales', 'Sales'), ('Design', 'Design'), ('Backoffice', 'Backoffice'), ('Marketing', 'Marketing'), ('Customer Service', 'Customer Service')], max_length=25),
        ),
    ]
