# Generated by Django 4.2.7 on 2024-03-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0006_delete_subtask_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Design', 'Design'), ('Sales', 'Sales'), ('Backoffice', 'Backoffice'), ('Customer Service', 'Customer Service'), ('Marketing', 'Marketing'), ('Media', 'Media')], max_length=25),
        ),
    ]
