# Generated by Django 4.2.7 on 2024-03-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0007_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Design', 'Design'), ('Media', 'Media'), ('Backoffice', 'Backoffice'), ('Sales', 'Sales'), ('Customer Service', 'Customer Service'), ('Marketing', 'Marketing')], max_length=25),
        ),
    ]
