# Generated by Django 4.2.7 on 2024-03-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0008_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Design', 'Design'), ('Media', 'Media'), ('Customer Service', 'Customer Service'), ('Backoffice', 'Backoffice')], max_length=25),
        ),
    ]
