# Generated by Django 4.2.7 on 2024-03-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0009_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Design', 'Design'), ('Backoffice', 'Backoffice'), ('Media', 'Media'), ('Marketing', 'Marketing'), ('Customer Service', 'Customer Service')], max_length=25),
        ),
    ]
