# Generated by Django 4.2.7 on 2024-03-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0011_contact_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Media', 'Media'), ('Design', 'Design'), ('Customer Service', 'Customer Service'), ('Backoffice', 'Backoffice'), ('Marketing', 'Marketing'), ('Sales', 'Sales')], max_length=25),
        ),
    ]
